name: 'Build action'
description: 'Make release build'
author: 'Nemirova Dasha'
inputs:
  github-ref:
    description: 'This is commit sha'
    required: true
runs:
  using: 'node16'
  main: 'actions/build.js'