name: check files
run-name: Check files on TypeScript and linter errors
on:
  push:
    branches:
      - "*"
jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Install packages
        run: npm install
      - name: Run ts check
        run: ./actions/ts-check.sh

  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Install packages
        run: npm install
      - name: Run linter check
        run: ./actions/linter-check.sh