name: check files
run-name: "Проверка файлов на ошибки eslint + ts"
on:
  push:
    branches:
      - "*"
jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: "Установка пакетов"
        run: npm install
      - name: "Проверка ts файлов"
        run: ./actions/ts-check.sh

  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: "Установка пакетов"
        run: npm install
      - name: "Проверка eslint"
        run: ./actions/linter-check.sh